-- Config tables migrated from SQLite so Neon is the single source of truth for the
-- web dashboard. Operational counters stay in SQLite (shop_items.sold -> shop_stock).
-- Idempotent (IF NOT EXISTS): safe to re-apply.

CREATE TABLE IF NOT EXISTS self_role_panels (
    id            TEXT PRIMARY KEY,
    guild_id      TEXT NOT NULL,
    title         TEXT NOT NULL,
    description   TEXT,
    style         TEXT NOT NULL DEFAULT 'buttons',
    unique_choice BOOLEAN NOT NULL DEFAULT false,
    channel_id    TEXT,
    message_id    TEXT,
    enabled       BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_self_role_panels_guild ON self_role_panels (guild_id);

CREATE TABLE IF NOT EXISTS self_role_options (
    panel_id TEXT NOT NULL,
    role_id  TEXT NOT NULL,
    label    TEXT NOT NULL,
    emoji    TEXT,
    position INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (panel_id, role_id)
);

CREATE TABLE IF NOT EXISTS level_rewards (
    guild_id TEXT NOT NULL,
    level    INTEGER NOT NULL,
    role_id  TEXT NOT NULL,
    PRIMARY KEY (guild_id, level)
);

CREATE TABLE IF NOT EXISTS quiz_questions (
    id       TEXT PRIMARY KEY,
    guild_id TEXT NOT NULL,
    question TEXT NOT NULL,
    correct  TEXT NOT NULL,
    wrong1   TEXT NOT NULL,
    wrong2   TEXT NOT NULL,
    wrong3   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_quiz_guild ON quiz_questions (guild_id);

CREATE TABLE IF NOT EXISTS shop_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id    TEXT NOT NULL,
    type        TEXT NOT NULL,
    role_id     TEXT,
    name        TEXT NOT NULL,
    description TEXT,
    price       BIGINT NOT NULL,
    duration_s  BIGINT,
    stock       INTEGER,
    per_user    INTEGER,
    enabled     BOOLEAN NOT NULL DEFAULT true,
    created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_shop_items_guild ON shop_items (guild_id);

CREATE TABLE IF NOT EXISTS fac_action_types (
    id             TEXT PRIMARY KEY,
    guild_id       TEXT NOT NULL,
    name           TEXT NOT NULL,
    max_contingent INTEGER NOT NULL DEFAULT 0,
    min_contingent INTEGER NOT NULL DEFAULT 0,
    dirty_money    INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_action_types_guild_name ON fac_action_types (guild_id, name);
